#!/bin/bash

print_usage() {
  printf "Syntax: $0 <xsl-plugin> <mcp-file-to-export>\n"
}
# ----------------------------------------------------------------------

if [ "$1" == "" -o "$2" == "" ]
then
  print_usage
  exit 1
fi

xsltproc "$1" "$2"
